### ISSUE TITLE
Reproduction of SPFormer on the s3dis dataset

### ISSUE THREAD

**Issue by dq73** [kasparas-k/synthe-GUI#1]
I noticed recently that you added the code of generating superpoints of s3dis for SPFormer. May I ask if you have reproduced the result of SPFormer in s3dis now? Can you share your related codes? Thanks a lot.

**Comment by kasparas-k** [comment]
> I noticed recently that you added the code of generating superpoints of s3dis for SPFormer. May I ask if you have reproduced the result of SPFormer in s3dis now? Can you share your related codes? Thanks a lot.

This is the wrong repository for this issue. Synthe-GUI is unrelated astrophysics software.

I have not tried training the model or reproducing results.

**Comment by dq73** [comment]
OK, THanks!
